# Generated by Django 5.2.9 on 2025-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True,
                help_text="Books saved for later purchase.",
                related_name="wishlisted_by",
                to="core.book",
                verbose_name="wishlist",
            ),
        ),
    ]
