# Generated by Django 5.2.9 on 2025-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="Unique referral code for this user.",
                max_length=11,
                null=True,
                unique=True,
                verbose_name="referral code",
            ),
        ),
    ]
