# Generated by Django 5.2.9 on 2025-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_referral_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive email notifications for purchases, updates, etc.",
                verbose_name="email notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reading_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Receive reminders to continue reading books.",
                verbose_name="reading reminders",
            ),
        ),
    ]
