# Generated by Django 5.2.9 on 2026-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fr", "Français")],
                help_text="Preferred interface language.",
                max_length=10,
                verbose_name="preferred language",
            ),
        ),
    ]
