# Generated by Django 5.2.9 on 2025-12-06 23:07

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the book.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title.",
                        max_length=280,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief description for listings (max 200 characters).",
                        max_length=200,
                        verbose_name="short description",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        help_text="Full description for the book detail page.",
                        verbose_name="long description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("romance", "Romance"),
                            ("thriller_mystery", "Thriller & Mystery"),
                            ("drama", "Drama"),
                            ("scifi_fantasy", "Science Fiction & Fantasy"),
                            ("horror", "Horror"),
                            ("course", "Course"),
                            ("politics", "Politics"),
                            ("non_fiction", "Non-Fiction"),
                            ("biography_memoir", "Biography & Memoir"),
                            ("self_help", "Self-Help & Personal Development"),
                            ("business_money", "Business & Money"),
                            ("history", "History"),
                            ("health_wellness", "Health & Wellness"),
                            ("religion_spirituality", "Religion & Spirituality"),
                            ("children_ya", "Children & Young Adult"),
                            ("poetry", "Poetry"),
                            ("academic", "Academic & Educational"),
                            ("african_literature", "African Literature & Culture"),
                        ],
                        default="fiction",
                        help_text="Book category.",
                        max_length=30,
                        verbose_name="category",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        help_text="Primary language of the book.",
                        max_length=5,
                        verbose_name="language",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Price in XAF (0 for free books).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("ebook_ready", "Ebook Ready"),
                            ("audiobook_generated", "Audiobook Generated"),
                            ("completed", "Completed"),
                        ],
                        default="in_review",
                        help_text="Current status in the publishing workflow.",
                        max_length=25,
                        verbose_name="status",
                    ),
                ),
                (
                    "denial_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for denial (if status is Denied).",
                        verbose_name="denial reason",
                    ),
                ),
                (
                    "commission_rate",
                    models.IntegerField(
                        choices=[(10, "10%"), (30, "30%")],
                        default=10,
                        help_text="Platform commission rate percentage.",
                        verbose_name="commission rate",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the book was submitted.",
                        verbose_name="submission date",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True,
                        help_text="When the book was approved.",
                        null=True,
                        verbose_name="approval date",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True,
                        help_text="When all conversions were completed.",
                        null=True,
                        verbose_name="completion date",
                    ),
                ),
                (
                    "manuscript_file",
                    models.FileField(
                        help_text="Original manuscript file (PDF, DOCX, EPUB, TXT).",
                        upload_to=core.models.manuscript_upload_path,
                        verbose_name="manuscript file",
                    ),
                ),
                (
                    "ebook_file",
                    models.FileField(
                        blank=True,
                        help_text="Converted ebook file.",
                        null=True,
                        upload_to=core.models.ebook_upload_path,
                        verbose_name="ebook file",
                    ),
                ),
                (
                    "audiobook_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated audiobook file.",
                        null=True,
                        upload_to=core.models.audiobook_upload_path,
                        verbose_name="audiobook file",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Book cover image.",
                        upload_to=core.models.cover_upload_path,
                        verbose_name="cover image",
                    ),
                ),
                (
                    "total_sales",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of copies sold.",
                        verbose_name="total sales",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average rating (0-5 stars).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author/publisher of this book.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="LibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last accessed"
                    ),
                ),
                (
                    "reading_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current page number for ebook reading.",
                        verbose_name="reading progress",
                    ),
                ),
                (
                    "listening_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current position in seconds for audiobook.",
                        verbose_name="listening progress",
                    ),
                ),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("not_downloaded", "Not Downloaded"),
                            ("downloaded", "Downloaded"),
                            ("outdated", "Outdated"),
                        ],
                        default="not_downloaded",
                        max_length=20,
                        verbose_name="download status",
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=15,
                        verbose_name="completion status",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_entries",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "library entry",
                "verbose_name_plural": "library entries",
                "ordering": ["-date_added"],
            },
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to withdraw in XAF (minimum 5,000 XAF).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("5000.00"))
                        ],
                        verbose_name="amount requested",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="request date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=15,
                        verbose_name="payout method",
                    ),
                ),
                (
                    "account_details",
                    models.TextField(
                        help_text="Phone number for mobile money or bank account details.",
                        verbose_name="account details",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for processing (admin only).",
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True,
                        help_text="When the payout was completed.",
                        null=True,
                        verbose_name="completion date",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "payout request",
                "verbose_name_plural": "payout requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="purchase date"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid in XAF.",
                        max_digits=10,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe (Card)"),
                            ("fapshi", "Fapshi (Mobile Money)"),
                        ],
                        max_length=10,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction reference.",
                        max_length=255,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission amount for the platform.",
                        max_digits=10,
                        verbose_name="platform commission",
                    ),
                ),
                (
                    "author_earning",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Earning amount for the author.",
                        max_digits=10,
                        verbose_name="author earning",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 to 5 stars.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional written review.",
                        verbose_name="review text",
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(auto_now_add=True, verbose_name="date posted"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the review is publicly visible.",
                        verbose_name="is visible",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "ordering": ["-date_posted"],
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["status"], name="core_book_status_278294_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["category"], name="core_book_categor_e152e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["language"], name="core_book_languag_211dc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="core_book_author__9ad2d3_idx"),
        ),
        migrations.AddIndex(
            model_name="libraryentry",
            index=models.Index(
                fields=["user", "book"], name="core_librar_user_id_f5a9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="libraryentry",
            index=models.Index(
                fields=["completion_status"], name="core_librar_complet_7ceb82_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryentry",
            constraint=models.UniqueConstraint(
                fields=("user", "book"), name="unique_user_book_library"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrequest",
            index=models.Index(
                fields=["author"], name="core_payout_author__450bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrequest",
            index=models.Index(fields=["status"], name="core_payout_status_7f2d4c_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["buyer"], name="core_purcha_buyer_i_c20243_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["book"], name="core_purcha_book_id_c77d64_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["payment_status"], name="core_purcha_payment_6cf1cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["book", "is_visible"], name="core_review_book_id_2c8b0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "book"), name="unique_user_book_review"
            ),
        ),
    ]
