# Generated by Django 5.2.9 on 2025-12-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardCopyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="request date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Name for delivery",
                        max_length=200,
                        verbose_name="full name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact phone number",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        help_text="Full delivery address including city, region, and any landmarks",
                        verbose_name="shipping address",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any special instructions for delivery",
                        verbose_name="additional notes",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for processing",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Shipping tracking number if applicable",
                        max_length=100,
                        verbose_name="tracking number",
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed date"
                    ),
                ),
                (
                    "shipped_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="shipped date"
                    ),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered date"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardcopy_requests",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardcopy_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "hard copy request",
                "verbose_name_plural": "hard copy requests",
                "ordering": ["-request_date"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="core_hardco_user_id_3b0cea_idx"
                    ),
                    models.Index(
                        fields=["book"], name="core_hardco_book_id_cdce9f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_hardco_status_c46a8c_idx"
                    ),
                ],
            },
        ),
    ]
