# Generated by Django 5.2.9 on 2025-12-23 23:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_hardcopyrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UpfrontPaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount requested in XAF.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1000.00"))
                        ],
                        verbose_name="amount requested",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why you need this advance payment.",
                        verbose_name="reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_review",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if applicable.",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "repayment_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Extra percentage taken per sale to recoup advance (e.g., 20 means +20%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("50.00")),
                        ],
                        verbose_name="repayment rate",
                    ),
                ),
                (
                    "amount_recouped",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount recouped from sales so far.",
                        max_digits=12,
                        verbose_name="amount recouped",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for admin review.",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Author has accepted the terms and conditions.",
                        verbose_name="terms accepted",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author applying for upfront payment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upfront_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific book for the advance, or null for all books.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upfront_applications",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
            ],
            options={
                "verbose_name": "upfront payment application",
                "verbose_name_plural": "upfront payment applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author"], name="core_upfron_author__ace580_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_upfron_status_f6f449_idx"
                    ),
                ],
            },
        ),
    ]
