# Generated by Django 5.2.9 on 2025-12-24 00:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_upfront_payment_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Donation amount in XAF (min 500, max 327,500).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("500.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("327500.00")
                            ),
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Personal message to the author.",
                        max_length=500,
                        verbose_name="message",
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="User accepted donation terms.",
                        verbose_name="terms accepted",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe (Card)"),
                            ("fapshi", "Fapshi (Mobile Money)"),
                        ],
                        default="fapshi",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction ID.",
                        max_length=255,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Platform commission (10%).",
                        max_digits=12,
                        verbose_name="platform commission",
                    ),
                ),
                (
                    "author_earning",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount received by author (90%).",
                        max_digits=12,
                        verbose_name="author earning",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Book that inspired this donation (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        help_text="User who made the donation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="donor",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Author receiving the donation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "donation",
                "verbose_name_plural": "donations",
                "ordering": ["-created_at"],
            },
        ),
    ]
