# Generated by Django 5.2.9 on 2025-12-24 09:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_donation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Percentage of sale that goes to referrer (deducted from author share).",
                        max_digits=5,
                        verbose_name="referral commission percent",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable the referral system.",
                        verbose_name="referral system active",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral settings",
                "verbose_name_plural": "referral settings",
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="referral_commission",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Commission paid to referrer.",
                max_digits=10,
                verbose_name="referral commission",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who referred this purchase.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="referred by",
            ),
        ),
    ]
