# Generated by Django 5.2.9 on 2025-12-24 10:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_referral_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ebook_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Platform commission for ebook-only purchases (default 10%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="ebook commission percent",
                    ),
                ),
                (
                    "audiobook_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="Platform commission for purchases with audiobook (default 30%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="audiobook commission percent",
                    ),
                ),
                (
                    "donation_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Platform commission for donations (default 10%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="donation commission percent",
                    ),
                ),
            ],
            options={
                "verbose_name": "commission settings",
                "verbose_name_plural": "commission settings",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="custom_commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional custom commission rate. If set, overrides global settings.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="custom commission rate",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="commission_rate",
            field=models.IntegerField(
                choices=[(10, "10%"), (30, "30%")],
                default=10,
                help_text="Platform commission rate percentage (for legacy compatibility).",
                verbose_name="commission rate",
            ),
        ),
    ]
