# Generated by Django 5.2.9 on 2025-12-24 11:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_commission_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="balance_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount paid from user account balance.",
                max_digits=10,
                verbose_name="balance used",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe (Card)"),
                    ("fapshi", "Fapshi (Mobile Money)"),
                    ("balance", "Account Balance"),
                    ("partial", "Partial (Balance + Gateway)"),
                ],
                max_length=15,
                verbose_name="payment method",
            ),
        ),
    ]
