# Generated by Django 5.2.9 on 2025-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_balance_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="hard_copy_option",
            field=models.CharField(
                choices=[
                    ("none", "No hard copies - Ebook/Audiobook only"),
                    ("author", "I have hard copies to ship"),
                    ("xanula", "Xanula should produce hard copies"),
                ],
                default="none",
                help_text="Hard copy availability option.",
                max_length=10,
                verbose_name="hard copy option",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_cover_design",
            field=models.BooleanField(
                default=False,
                help_text="Author wants Xanula to design/redesign the book cover.",
                verbose_name="wants cover design",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_editor_services",
            field=models.BooleanField(
                default=False,
                help_text="Author wants Xanula editing/proofreading services.",
                verbose_name="wants editor services",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_formatting",
            field=models.BooleanField(
                default=False,
                help_text="Author wants Xanula to format the book layout.",
                verbose_name="wants formatting",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_marketing_kit",
            field=models.BooleanField(
                default=False,
                help_text="Author wants social media marketing materials.",
                verbose_name="wants marketing kit",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_third_party_distribution",
            field=models.BooleanField(
                default=False,
                help_text="Author wants distribution to Amazon KDP, REEPLS, Smashwords, etc.",
                verbose_name="wants third-party distribution",
            ),
        ),
    ]
