# Generated by Django 5.2.9 on 2025-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_publishing_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated QR code linking to book page.",
                null=True,
                upload_to="qr_codes/",
                verbose_name="QR code",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wants_isbn",
            field=models.BooleanField(
                default=False,
                help_text="Author wants ISBN for printed book (increases commission).",
                verbose_name="wants ISBN",
            ),
        ),
    ]
