# Generated by Django 5.2.9 on 2025-12-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_isbn_and_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        help_text="The language section this book appears in.",
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Display order (1-6). Lower numbers appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this featured book is currently shown.",
                        verbose_name="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Select a published book to feature.",
                        limit_choices_to={
                            "status__in": [
                                "approved",
                                "ebook_ready",
                                "audiobook_generated",
                                "completed",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="core.book",
                        verbose_name="book",
                    ),
                ),
            ],
            options={
                "verbose_name": "featured book",
                "verbose_name_plural": "featured books",
                "ordering": ["language", "position"],
                "unique_together": {("language", "position")},
            },
        ),
    ]
