# Generated by Django 5.2.9 on 2025-12-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_featured_books"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("book_status", "Book Status Change"),
                            ("new_sale", "New Sale"),
                            ("new_review", "New Review"),
                            ("new_donation", "Donation Received"),
                            ("payout_status", "Payout Status"),
                            ("upfront_status", "Upfront Payment Status"),
                            ("ebook_ready", "Ebook Ready"),
                            ("audiobook_ready", "Audiobook Ready"),
                            ("purchase_confirmed", "Purchase Confirmed"),
                            ("book_added", "Book Added to Library"),
                            ("wishlist_price", "Wishlist Price Drop"),
                            ("hard_copy", "Hard Copy Update"),
                            ("referral_earned", "Referral Commission"),
                            ("system", "System Notification"),
                            ("welcome", "Welcome"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short notification title.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Full notification message.", verbose_name="message"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🔔",
                        help_text="Emoji icon for the notification.",
                        max_length=10,
                        verbose_name="icon",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "related_book_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of related book, if any.",
                        null=True,
                        verbose_name="related book ID",
                    ),
                ),
                (
                    "related_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate to when clicked.",
                        max_length=500,
                        verbose_name="related URL",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="core_notifi_user_id_cb8f07_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_notifi_user_id_1cc5b6_idx",
                    ),
                ],
            },
        ),
    ]
