# Generated by Django 5.2.9 on 2026-02-26 00:43

import core.models.article
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=300)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Title (French)",
                    ),
                ),
                (
                    "subtitle_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Subtitle (French)",
                    ),
                ),
                (
                    "content_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", verbose_name="Content (French)"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.article.article_thumbnail_path,
                    ),
                ),
                (
                    "french_audio",
                    models.FileField(
                        blank=True,
                        help_text="French audio version of the article",
                        null=True,
                        upload_to=core.models.article.article_audio_path,
                    ),
                ),
                (
                    "english_audio",
                    models.FileField(
                        blank=True,
                        help_text="English audio version of the article",
                        null=True,
                        upload_to=core.models.article.article_audio_path,
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "send_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Check this to send email & in-app notifications when publishing. Uncheck to publish silently.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
    ]
