# Generated by Django 5.2.9 on 2026-05-01 18:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_article_complete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AITokenSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_initial_tokens", models.PositiveIntegerField(default=10000)),
                (
                    "usage_multiplier",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=8
                    ),
                ),
                ("minimum_request_tokens", models.PositiveIntegerField(default=25)),
                ("low_balance_threshold", models.PositiveIntegerField(default=1000)),
                ("base_bundle_tokens", models.PositiveIntegerField(default=5000)),
                ("base_price_xaf", models.PositiveIntegerField(default=1000)),
                (
                    "base_price_eur",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.00"), max_digits=8
                    ),
                ),
                ("custom_min_tokens", models.PositiveIntegerField(default=5000)),
                ("custom_step_tokens", models.PositiveIntegerField(default=1000)),
                (
                    "analyze_multiplier",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=8
                    ),
                ),
                (
                    "generate_multiplier",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=8
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI token settings",
                "verbose_name_plural": "AI token settings",
            },
        ),
        migrations.CreateModel(
            name="AITokenWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                ("total_granted", models.PositiveIntegerField(default=0)),
                ("total_purchased", models.PositiveIntegerField(default=0)),
                ("total_used", models.PositiveIntegerField(default=0)),
                ("free_grant_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI token wallet",
                "verbose_name_plural": "AI token wallets",
            },
        ),
        migrations.CreateModel(
            name="AITokenPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_amount", models.PositiveIntegerField()),
                ("amount_xaf", models.PositiveIntegerField()),
                ("amount_eur", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("fapshi", "Fapshi")],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("return_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI token purchase",
                "verbose_name_plural": "AI token purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "payment_status"],
                        name="core_aitoke_user_id_12d59b_idx",
                    ),
                    models.Index(
                        fields=["payment_transaction_id"],
                        name="core_aitoke_payment_80f29c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AITokenLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("free_grant", "Free grant"),
                            ("usage", "AI usage"),
                            ("purchase", "Purchase"),
                            ("refund", "Refund"),
                            ("admin_adjustment", "Admin adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("action", models.CharField(blank=True, max_length=50)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.aitokenwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI token ledger entry",
                "verbose_name_plural": "AI token ledger entries",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_aitoke_user_id_331149_idx",
                    ),
                    models.Index(
                        fields=["entry_type"], name="core_aitoke_entry_t_071d71_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="core_aitoke_referen_39397b_idx"
                    ),
                ],
            },
        ),
    ]
