# Generated by Django 5.2.9 on 2026-02-25 23:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_fr",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="", verbose_name="Content (French)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="subtitle_fr",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Subtitle (French)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_fr",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Title (French)"
            ),
        ),
    ]
