# Generated by Django 5.2.9 on 2026-05-01 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_aitokensettings_aitokenwallet_aitokenpurchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitokensettings",
            name="analyze_flat_tokens",
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name="aitokensettings",
            name="input_context_weight",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.005"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="aitokensettings",
            name="output_chars_per_token",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="aitokensettings",
            name="minimum_request_tokens",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
