# Generated by Django 5.2.9 on 2026-05-01 20:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_aitokensettings_analyze_flat_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitokensettings",
            name="xaf_per_eur",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("500.00"), max_digits=10
            ),
        ),
    ]
