# Generated by Django 5.2.9 on 2026-02-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_make_article_dates_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="send_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Check this to send email & in-app notifications when publishing. Uncheck to publish silently.",
            ),
        ),
    ]
