# Generated by Django 5.2.9 on 2026-05-01 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_aitokensettings_xaf_per_eur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aitokensettings",
            name="xaf_per_eur",
        ),
    ]
