# Generated by Django 5.2.9 on 2026-05-01 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_aitokensettings_xaf_per_eur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aitokensettings",
            name="base_price_eur",
        ),
    ]
