"""
Django settings for xanula_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import mimetypes
from pathlib import Path
from decouple import config, Csv
from django.utils.translation import gettext_lazy as _

# Fix MIME type for JavaScript modules (required for ES module imports)
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("application/javascript", ".mjs", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "storages",  # For Backblaze B2 (S3-compatible) storage
    "tailwind",
    "theme",  # Tailwind theme app
    "pwa",
    "django_q",
    "django_ckeditor_5",

    # Local apps
    "core",
    "users",
]

# Required for django-allauth
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files with correct MIME types
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # django-allauth middleware
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "xanula_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "xanula_project.wsgi.application"


# =============================================================================
# DATABASE
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =============================================================================
# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =============================================================================
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Douala"  # Cameroon timezone

USE_I18N = True

USE_TZ = True

# Languages available for the application
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# =============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# =============================================================================

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise settings for static files (proper MIME types for ES modules)
WHITENOISE_USE_FINDERS = True  # Use finders in DEBUG mode
WHITENOISE_MIMETYPES = {
    '.js': 'application/javascript',
    '.mjs': 'application/javascript',
}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "users.User"


# =============================================================================
# MEDIA FILES (User uploads)
# =============================================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# BACKBLAZE B2 CLOUD STORAGE CONFIGURATION
# Cloud storage for all uploads (manuscripts, ebooks, audiobooks, covers, etc.)
# Uses S3-compatible API via django-storages
# =============================================================================

# Backblaze B2 credentials (from .env)
AWS_ACCESS_KEY_ID = config('BACKBLAZE_APPLICATION_ID', default='')
AWS_SECRET_ACCESS_KEY = config('BACKBLAZE_APPLICATION_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('BACKBLAZE_BUCKET_NAME', default='XANULA')

# Backblaze B2 S3-compatible endpoint
# Format: s3.{region}.backblazeb2.com
AWS_S3_ENDPOINT_URL = config('BACKBLAZE_ENDPOINT_URL', default='https://s3.eu-central-003.backblazeb2.com')
AWS_S3_REGION_NAME = config('BACKBLAZE_REGION', default='eu-central-003')

# S3 settings for Backblaze B2
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'  # Files are publicly readable
AWS_QUERYSTRING_AUTH = False  # Don't add auth params to URLs (public bucket)

# Custom domain for serving files (optional, uses B2 URL by default)
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.eu-central-003.backblazeb2.com'

# Use Django 4.2+ STORAGES configuration
# This sets Backblaze B2 as the default storage for all FileField/ImageField uploads
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# =============================================================================
# DJANGO-ALLAUTH CONFIGURATION
# https://docs.allauth.org/en/latest/
# =============================================================================

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Account settings (using new allauth settings format)
# Custom User model uses email instead of username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"

# Session settings (per Architecture Document Section 4)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True  # HttpOnly cookies (per Architecture Document Section 18)
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies in production

# Social account settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}


# =============================================================================
# DJANGO-TAILWIND CONFIGURATION
# =============================================================================

TAILWIND_APP_NAME = "theme"

# For django-tailwind to work with browser reload
INTERNAL_IPS = [
    "127.0.0.1",
]

# NPM executable path (adjust if needed for your system)
# NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"


# =============================================================================
# DJANGO-PWA CONFIGURATION
# https://github.com/silviolleite/django-pwa
# =============================================================================

PWA_APP_NAME = "Xanula"
PWA_APP_DESCRIPTION = "Your gateway to African literature - discover, read, and listen to books"
PWA_APP_THEME_COLOR = "#8B2635"
PWA_APP_BACKGROUND_COLOR = "#8B2635"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_ICONS = [
    {
        "src": "/static/images/icons/icon-192x192.png",
        "sizes": "192x192",
        "type": "image/png",
        "purpose": "any maskable",
    },
    {
        "src": "/static/images/icons/icon-512x512.png",
        "sizes": "512x512",
        "type": "image/png",
        "purpose": "any maskable",
    },
]
PWA_APP_ICONS_APPLE = [
    {
        "src": "/static/images/icons/icon-192x192.png",
        "sizes": "192x192",
        "type": "image/png",
    },
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "/static/images/icons/splash-640x1136.png",
        "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
    },
]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "en-US"
PWA_SERVICE_WORKER_PATH = BASE_DIR / "static" / "js" / "serviceworker.js"


# =============================================================================
# DJANGO-Q CONFIGURATION (Background Tasks)
# https://django-q.readthedocs.io/
# =============================================================================

Q_CLUSTER = {
    "name": "xanula",
    "workers": 2,
    "recycle": 500,
    "timeout": 60,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q",
    "orm": "default",
}


# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================

# Use console backend for development (emails printed to terminal)
# Switch to SMTP backend in production
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="reepls.project@gmail.com")

# Site URL for emails
SITE_URL = config("SITE_URL", default="http://localhost:8000")

# =============================================================================
# PAYMENT GATEWAY CONFIGURATION
# =============================================================================

# Stripe
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")

# Fapshi (Mobile Money)
FAPSHI_API_KEY = config("FAPSHI_API_KEY", default="")
FAPSHI_SECRET_KEY = config("FAPSHI_SECRET_KEY", default="")


# =============================================================================
# LOGGING CONFIGURATION
# Per Architecture Document Section 21
# =============================================================================

LOG_DIR = BASE_DIR / "logs"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "xanula.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        "xanula": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# =============================================================================
# FILE UPLOAD SETTINGS
# =============================================================================

# Maximum upload size (50MB for audiobooks)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Allowed file types for uploads
ALLOWED_MANUSCRIPT_TYPES = [".pdf", ".docx", ".epub", ".txt"]
ALLOWED_AUDIO_TYPES = [".mp3", ".m4a"]
ALLOWED_IMAGE_TYPES = [".jpg", ".jpeg", ".png", ".webp"]


# =============================================================================
# STRIPE PAYMENT CONFIGURATION
# =============================================================================

STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')


# =============================================================================
# FAPSHI PAYMENT CONFIGURATION (Mobile Money)
# =============================================================================

FAPSHI_API_USER = config('FAPSHI_API_USER', default='')
FAPSHI_API_KEY = config('FAPSHI_API_KEY', default='')
FAPSHI_BASE_URL = config('FAPSHI_BASE_URL', default='https://live.fapshi.com')


# =============================================================================
# EMAIL CONFIGURATION (Additional)
# =============================================================================

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='reepls.project@gmail.com')

# SMTP settings for production (uncomment and configure in .env)
# EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')


# =============================================================================
# CKEDITOR 5 CONFIGURATION
# =============================================================================

customColorPalette = [
    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'},
    {'color': '#722F37', 'label': 'Burgundy'},
    {'color': '#2D4739', 'label': 'Forest'},
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontColor', '|',
            'bulletedList', 'numberedList', 'blockQuote', '|',
            'link', 'insertImage', 'mediaEmbed', '|',
            'undo', 'redo',
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:alignLeft',
                'imageStyle:alignRight', 'imageStyle:alignCenter',
                'imageStyle:side',
            ],
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'},
            ]
        },
    },
}

CKEDITOR_5_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

