# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="ai_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="ai_memory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="ai_profile_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
